server:
  port: 8082
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/gitpolio"
    username: "root"
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: gitpolio.bot@gmail.com
    password: gitpolioXF2SL#
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000